### ISSUE TITLE
[1.16.5] endless latest.log errors.

### ISSUE THREAD

**Issue by Darkmega18** [FuGu0416/Fishs_Undead_Rising#102]
For version 2.0.1 in 1.16.5 I'm getting an endless spam of similar stuff like this in my logs.

```
[03:07:51] [main/INFO]: [com.Fishmod.mod_LavaCow.events.EventHandler:onEntityJoinWorld:520]: java.lang.NoSuchFieldException: availableGoals
[03:07:51] [main/INFO]: [com.Fishmod.mod_LavaCow.events.EventHandler:onEntityJoinWorld:520]: 	at java.lang.Class.getDeclaredField(Class.java:2070)
[03:07:51] [main/INFO]: [com.Fishmod.mod_LavaCow.events.EventHandler:onEntityJoinWorld:520]: 	at com.Fishmod.mod_LavaCow.events.EventHandler.onEntityJoinWorld(EventHandler.java:472)
[03:07:51] [main/INFO]: [com.Fishmod.mod_LavaCow.events.EventHandler:onEntityJoinWorld:520]: 	at net.minecraftforge.eventbus.ASMEventHandler_2215_EventHandler_onEntityJoinWorld_EntityJoinWorldEvent.invoke(.dynamic)
[03:07:51] [main/INFO]: [com.Fishmod.mod_LavaCow.events.EventHandler:onEntityJoinWorld:520]: 	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
[03:07:51] [main/INFO]: [com.Fishmod.mod_LavaCow.events.EventHandler:onEntityJoinWorld:520]: 	at net.minecraftforge.eventbus.EventBus$$Lambda$3363/632233407.invoke(Unknown Source)
[03:07:51] [main/INFO]: [com.Fishmod.mod_LavaCow.events.EventHandler:onEntityJoinWorld:520]: 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
[03:07:51] [main/INFO]: [com.Fishmod.mod_LavaCow.events.EventHandler:onEntityJoinWorld:520]: 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
[03:07:51] [main/INFO]: [com.Fishmod.mod_LavaCow.events.EventHandler:onEntityJoinWorld:520]: 	at net.minecraft.client.world.ClientWorld.func_217424_b(ClientWorld.java:291)
[03:07:51] [main/INFO]: [com.Fishmod.mod_LavaCow.events.EventHandler:onEntityJoinWorld:520]: 	at net.minecraft.client.world.ClientWorld.func_217411_a(ClientWorld.java:287)
[03:07:51] [main/INFO]: [com.Fishmod.mod_LavaCow.events.EventHandler:onEntityJoinWorld:520]: 	at net.minecraft.client.network.play.ClientPlayNetHandler.func_147281_a(ClientPlayNetHandler.java:873)
[03:07:51] [main/INFO]: [com.Fishmod.mod_LavaCow.events.EventHandler:onEntityJoinWorld:520]: 	at net.minecraft.network.play.server.SSpawnMobPacket.func_148833_a(SourceFile:90)
[03:07:51] [main/INFO]: [com.Fishmod.mod_LavaCow.events.EventHandler:onEntityJoinWorld:520]: 	at net.minecraft.network.play.server.SSpawnMobPacket.func_148833_a(SourceFile:14)
[03:07:51] [main/INFO]: [com.Fishmod.mod_LavaCow.events.EventHandler:onEntityJoinWorld:520]: 	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21)
[03:07:51] [main/INFO]: [com.Fishmod.mod_LavaCow.events.EventHandler:onEntityJoinWorld:520]: 	at net.minecraft.network.PacketThreadUtil$$Lambda$31530/2057908148.run(Unknown Source)
[03:07:51] [main/INFO]: [com.Fishmod.mod_LavaCow.events.EventHandler:onEntityJoinWorld:520]: 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144)
[03:07:51] [main/INFO]: [com.Fishmod.mod_LavaCow.events.EventHandler:onEntityJoinWorld:520]: 	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
[03:07:51] [main/INFO]: [com.Fishmod.mod_LavaCow.events.EventHandler:onEntityJoinWorld:520]: 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118)
[03:07:51] [main/INFO]: [com.Fishmod.mod_LavaCow.events.EventHandler:onEntityJoinWorld:520]: 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103)
[03:07:51] [main/INFO]: [com.Fishmod.mod_LavaCow.events.EventHandler:onEntityJoinWorld:520]: 	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:948)
[03:07:51] [main/INFO]: [com.Fishmod.mod_LavaCow.events.EventHandler:onEntityJoinWorld:520]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607)
[03:07:51] [main/INFO]: [com.Fishmod.mod_LavaCow.events.EventHandler:onEntityJoinWorld:520]: 	at net.minecraft.client.main.Main.main(Main.java:184)
[03:07:51] [main/INFO]: [com.Fishmod.mod_LavaCow.events.EventHandler:onEntityJoinWorld:520]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[03:07:51] [main/INFO]: [com.Fishmod.mod_LavaCow.events.EventHandler:onEntityJoinWorld:520]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[03:07:51] [main/INFO]: [com.Fishmod.mod_LavaCow.events.EventHandler:onEntityJoinWorld:520]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[03:07:51] [main/INFO]: [com.Fishmod.mod_LavaCow.events.EventHandler:onEntityJoinWorld:520]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[03:07:51] [main/INFO]: [com.Fishmod.mod_LavaCow.events.EventHandler:onEntityJoinWorld:520]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
[03:07:51] [main/INFO]: [com.Fishmod.mod_LavaCow.events.EventHandler:onEntityJoinWorld:520]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$502/1944370016.call(Unknown Source)
[03:07:51] [main/INFO]: [com.Fishmod.mod_LavaCow.events.EventHandler:onEntityJoinWorld:520]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[03:07:51] [main/INFO]: [com.Fishmod.mod_LavaCow.events.EventHandler:onEntityJoinWorld:520]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[03:07:51] [main/INFO]: [com.Fishmod.mod_LavaCow.events.EventHandler:onEntityJoinWorld:520]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[03:07:51] [main/INFO]: [com.Fishmod.mod_LavaCow.events.EventHandler:onEntityJoinWorld:520]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[03:07:51] [main/INFO]: [com.Fishmod.mod_LavaCow.events.EventHandler:onEntityJoinWorld:520]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
```

would you need a full log? it's mostly that repeating over and over.

I have quite the large modpack...

but the forge version is 1.16.5, 36.2.33

**Comment by Jackiecrazy** [comment]
I had a quick look inside the source code since it was available. Instead of deleting skeleton AI and replacing it with a version that checks for crowns (which doesn't survive the obfuscation process and leads to the above error, unless you include the alias or write a mixin), it would be faster to cancel the targeting in LivingSetAttackEvent.

比起直接用自己的AI替代原版骷髅的AI，建议还是在LivingSetAttackEvent检查攻击者是不是骷髅和目标（检查null）有没有戴着王冠，然后`mob.setAttackTarget(null)`。这样比较不容易出兼容问题和诡异的bug。

**Comment by FuGu0416** [comment]
I've tried this solution before. The skeleton would stuck in an infinite loop where it set player as target then got cleared by the event. It ends up just twitching in place.

我有試過這個做法，但這會導致骷髏的AI不斷地將玩家設為攻擊目標而後又被清除，只能停在原地抖動。

Thanks for your suggestion anyway 😉

**Comment by Darkmega18** [comment]
doesn't it have ways to cancel it from selecting the target at all under certain conditions in the first place? fairly sure jackie here does a lot of attack target nulling and other control stuff with his stealth component for war dance and stuff.

**Comment by FuGu0416** [comment]
Hmm, maybe there's some flaw in my previous approach (the set null one). I'll look into that, thanks!

**Comment by Darkmega18** [comment]
hopefully you can find it. 
I'd definitely like to include this mod in my pack once it's stable in 1.16.5. I literally said to my friends I work on the pack with the other night: "I wish fish's undead rising was in 1.16.5". and then a little later, someone shows me it's been updated to 1.16.5, 5 hours ago.  it's meant to be. :3

**Comment by Jackiecrazy** [comment]
哦，對了！如果還想要骷髏反擊的話，可以修改LivingVisibilityEvent，檢測骷髏和王冠的時候e.setVisibility(0)。這樣骷髏就無法偵測到玩家了。

**Comment by FuGu0416** [comment]
version 2.0.2 should fix this issue.

**Comment by Darkmega18** [comment]
excellent.
