### ISSUE TITLE
Crash when using Raven Whistle

### ISSUE THREAD

**Issue by EmoryM** [FuGu0416/Fishs_Undead_Rising#7]
[05:03:14] [Server thread/FATAL] [minecraft/MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_191]
        at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_191]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
Caused by: java.lang.NullPointerException
        at com.Fishmod.mod_LavaCow.item.ItemRavenWhistle.func_111207_a(ItemRavenWhistle.java:87) ~[ItemRavenWhistle.class:?]
        at net.minecraft.item.ItemStack.func_111282_a(ItemStack.java:391) ~[aip.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_190775_a(EntityPlayer.java:1220) ~[aed.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:1075) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:69) ~[li.class:?]
        at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:13) ~[li.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_191]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_191]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more

**Comment by EmoryM** [comment]
Sorry - a little more info - didn't have a Raven tamed yet.  Version 1.1.0 of the mod in Minecraft 1.12.2.
